"""Conexión a la base de datos de Autoorigen: PostgreSQL (Supabase self-hosted).

Antes esta app usaba SQLite (sqlite3). Para no reescribir models.py ni las
rutas, este módulo expone una "capa de compatibilidad" que imita lo que el
resto del código ya usaba de sqlite3:

  - db.execute(sql, params) con marcadores "?"  -> se traducen a "%s"
  - cur.lastrowid después de un INSERT          -> se obtiene con RETURNING id
  - filas con acceso por nombre y por posición  -> fila["id"] y fila[0]
  - db.executescript(), db.commit(), db.close()

Diferencia a tener en cuenta: iterar una fila (for x in fila / tuple(fila))
devuelve los NOMBRES de las columnas, no los valores como en sqlite3.Row.
"""
import re

import click
import psycopg
from flask import current_app, g

EVENTOS_TIMELINE_COLUMNAS = """
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id INTEGER NOT NULL REFERENCES ordenes(id) ON DELETE CASCADE,
    tipo TEXT NOT NULL CHECK (tipo IN (
        'nota', 'cambio_estado', 'hallazgo', 'foto', 'video', 'informe',
        'observacion_mecanico', 'comentario_cliente', 'video_ingreso'
    )),
    titulo TEXT NOT NULL,
    descripcion TEXT,
    medio_path TEXT,
    creado_por TEXT NOT NULL DEFAULT 'admin' CHECK (creado_por IN ('admin', 'app_movil')),
    creado_en TEXT NOT NULL
"""

TABLAS = [
    "contactos", "clientes", "vehiculos", "mecanicos", "admins", "api_tokens",
    "citas", "ordenes", "eventos_timeline", "medios", "informes",
]

# Supabase publica automáticamente el esquema "public" por su API REST.
# Activar RLS sin políticas bloquea ese acceso externo; la app se conecta
# como "postgres" (dueño de las tablas), así que no se ve afectada.
_RLS = "\n".join(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY;" for t in TABLAS)

SCHEMA = f"""
CREATE TABLE IF NOT EXISTS contactos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    telefono TEXT NOT NULL,
    tipo TEXT,
    marca TEXT,
    modelo TEXT,
    anio TEXT,
    problema TEXT,
    mensaje TEXT NOT NULL,
    creado_en TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS clientes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    telefono TEXT NOT NULL,
    email TEXT,
    creado_en TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_clientes_telefono ON clientes(telefono);

CREATE TABLE IF NOT EXISTS vehiculos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id INTEGER NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
    placa TEXT NOT NULL UNIQUE,
    marca TEXT,
    modelo TEXT,
    anio TEXT,
    color TEXT,
    combustible TEXT CHECK (combustible IN ('gasolina', 'hibrido', 'electrico')),
    codigo_acceso TEXT,
    creado_en TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS mecanicos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    nombre TEXT NOT NULL,
    activo INTEGER NOT NULL DEFAULT 1,
    creado_en TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS citas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id INTEGER NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
    vehiculo_id INTEGER REFERENCES vehiculos(id) ON DELETE SET NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('vehiculo', 'visita')),
    fecha TEXT NOT NULL,
    hora TEXT NOT NULL,
    servicio TEXT,
    notas TEXT,
    estado TEXT NOT NULL DEFAULT 'pendiente'
        CHECK (estado IN ('pendiente', 'confirmada', 'cancelada', 'completada')),
    creado_en TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ordenes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehiculo_id INTEGER NOT NULL REFERENCES vehiculos(id) ON DELETE CASCADE,
    tecnico_id INTEGER REFERENCES mecanicos(id) ON DELETE SET NULL,
    titulo TEXT NOT NULL,
    estado_actual TEXT NOT NULL DEFAULT 'recibido'
        CHECK (estado_actual IN (
            'recibido', 'diagnosticando', 'diagnosticado',
            'reparando', 'verificando', 'listo'
        )),
    kilometraje TEXT,
    kilometraje_aceite TEXT,
    creado_en TEXT NOT NULL,
    actualizado_en TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS eventos_timeline ({EVENTOS_TIMELINE_COLUMNAS});

CREATE TABLE IF NOT EXISTS medios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id INTEGER NOT NULL REFERENCES ordenes(id) ON DELETE CASCADE,
    evento_id INTEGER REFERENCES eventos_timeline(id) ON DELETE SET NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('foto', 'video')),
    archivo_path TEXT NOT NULL,
    creado_en TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS admins (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    rol TEXT NOT NULL DEFAULT 'admin' CHECK (rol IN ('admin', 'superadmin')),
    creado_en TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS api_tokens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_dispositivo TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    activo INTEGER NOT NULL DEFAULT 1,
    creado_en TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS informes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id INTEGER NOT NULL REFERENCES ordenes(id) ON DELETE CASCADE,
    tipo TEXT NOT NULL CHECK (tipo IN ('preliminar', 'final')),
    contenido TEXT NOT NULL,
    estado TEXT NOT NULL DEFAULT 'generado' CHECK (estado IN ('generado', 'aprobado', 'rechazado')),
    aprobado_por INTEGER REFERENCES admins(id) ON DELETE SET NULL,
    comentario_supervisor TEXT,
    creado_en TEXT NOT NULL,
    revisado_en TEXT
);

{_RLS}
"""


# --------------------------------------------------------------------------
# Capa de compatibilidad sqlite3 -> psycopg
# --------------------------------------------------------------------------

_ES_INSERT = re.compile(r"^\s*INSERT\b", re.IGNORECASE)


class Fila(dict):
    """Imita sqlite3.Row: acceso por nombre (fila["id"]) y por posición (fila[0])."""

    def __getitem__(self, clave):
        if isinstance(clave, int):
            return list(self.values())[clave]
        return super().__getitem__(clave)


def _fabrica_filas(cursor):
    nombres = [col.name for col in cursor.description] if cursor.description else []

    def crear(valores):
        return Fila(zip(nombres, valores))

    return crear


def _adaptar_sql(sql, hay_params):
    # Con parámetros, psycopg interpreta "%": se escapa y luego "?" pasa a "%s".
    if not hay_params:
        return sql
    return sql.replace("%", "%%").replace("?", "%s")


class _Cursor:
    def __init__(self, cursor, lastrowid=None):
        self._cursor = cursor
        self.lastrowid = lastrowid
        self.rowcount = cursor.rowcount

    def fetchone(self):
        return self._cursor.fetchone() if self._cursor.description else None

    def fetchall(self):
        return self._cursor.fetchall() if self._cursor.description else []

    def __iter__(self):
        return iter(self.fetchall())


class _Conexion:
    def __init__(self, conexion):
        self._conn = conexion

    def execute(self, sql, params=None):
        hay_params = bool(params)
        sql_pg = _adaptar_sql(sql, hay_params)

        agregar_returning = bool(_ES_INSERT.match(sql)) and "RETURNING" not in sql.upper()
        if agregar_returning:
            sql_pg = sql_pg.rstrip().rstrip(";") + " RETURNING id"

        # Savepoint: si esta consulta falla (y el código la atrapa con try),
        # la transacción sigue usable, como pasaba con SQLite.
        self._conn.execute("SAVEPOINT compat")
        cur = self._conn.cursor(row_factory=_fabrica_filas)
        try:
            cur.execute(sql_pg, params if hay_params else None)
        except Exception:
            self._conn.execute("ROLLBACK TO SAVEPOINT compat")
            raise
        self._conn.execute("RELEASE SAVEPOINT compat")

        lastrowid = None
        if agregar_returning:
            fila = cur.fetchone()
            lastrowid = fila["id"] if fila else None
        return _Cursor(cur, lastrowid)

    def executemany(self, sql, secuencia_params):
        for params in secuencia_params:
            self.execute(sql, params)

    def executescript(self, sql):
        # Sin parámetros, psycopg acepta varias sentencias separadas por ";".
        self._conn.execute(sql)

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()


# --------------------------------------------------------------------------
# Conexión por petición (igual que antes)
# --------------------------------------------------------------------------

def get_db():
    if "db" not in g:
        url = current_app.config.get("DATABASE_URL")
        if not url:
            raise RuntimeError(
                "Falta DATABASE_URL en el archivo .env del proyecto "
                "(cadena de conexión de Supabase)."
            )
        g.db = _Conexion(psycopg.connect(url))
    return g.db


def close_db(exception=None):
    db = g.pop("db", None)
    if db is not None:
        # Descarta lo que no se confirmó con commit(), igual que sqlite3 al cerrar.
        db.rollback()
        db.close()


def migrate_schema(db):
    """En PostgreSQL la base nace con la estructura final, así que ya no hace
    falta ajustar columnas ni reconstruir tablas como con SQLite. Solo se
    conserva lo que sigue teniendo sentido. Es segura de repetir."""

    # otp_codigos (verificación por SMS) ya no se usa en ningún lado.
    db.execute("DROP TABLE IF EXISTS otp_codigos")

    # Vehículos sin código de acceso: se les genera uno para que "Historia
    # mecánica del vehículo" siga funcionando para ellos.
    sin_codigo = db.execute(
        "SELECT id FROM vehiculos WHERE codigo_acceso IS NULL OR codigo_acceso = ''"
    ).fetchall()
    if sin_codigo:
        from . import models  # import diferido: models importa db, evita ciclo

        for fila in sin_codigo:
            db.execute(
                "UPDATE vehiculos SET codigo_acceso = ? WHERE id = ?",
                (models.generar_codigo_acceso(), fila["id"]),
            )
    db.commit()


def init_db():
    db = get_db()
    db.executescript(SCHEMA)
    db.commit()
    migrate_schema(db)


def init_app(app):
    app.teardown_appcontext(close_db)

    with app.app_context():
        init_db()

    @app.cli.command("crear-admin")
    @click.argument("usuario")
    @click.argument("password")
    @click.option(
        "--superadmin", "es_superadmin", is_flag=True, default=False,
        help="Crea el usuario con rol superadmin (puede gestionar otros admins y tokens de la app móvil).",
    )
    def crear_admin_cmd(usuario, password, es_superadmin):
        """Crea (o actualiza la contraseña de) un usuario admin del panel.

        El primer admin del sistema siempre se crea como superadmin, sin
        importar la bandera --superadmin, para que exista alguien capaz de
        gestionar el resto desde /admin/usuarios.
        """
        from werkzeug.security import generate_password_hash

        from . import models

        existente = models.obtener_admin_por_usuario(usuario)
        if existente:
            models.actualizar_password_admin(existente["id"], generate_password_hash(password))
            click.echo(f"Contraseña actualizada para el admin '{usuario}'.")
            return

        es_primero = models.contar_admins() == 0
        rol = "superadmin" if (es_primero or es_superadmin) else "admin"
        models.crear_admin(usuario, generate_password_hash(password), rol)
        etiqueta = " (superadmin)" if rol == "superadmin" else ""
        click.echo(f"Admin '{usuario}' creado{etiqueta}.")

    @app.cli.command("crear-tecnico")
    @click.argument("usuario")
    @click.argument("password")
    @click.argument("nombre")
    def crear_tecnico_cmd(usuario, password, nombre):
        """Crea (o actualiza la contraseña de) un mecánico con acceso a la app móvil."""
        from werkzeug.security import generate_password_hash

        from . import models

        existente = models.obtener_mecanico_por_usuario(usuario)
        if existente:
            models.actualizar_password_mecanico(existente["id"], generate_password_hash(password))
            click.echo(f"Contraseña actualizada para el técnico '{usuario}'.")
        else:
            models.crear_mecanico(usuario, generate_password_hash(password), nombre)
            click.echo(f"Técnico '{usuario}' ({nombre}) creado.")
